services:
  truynes-monitor:
    build:
      context: https://github.com/TRUYNES/mini-monitor.git#main
      args:
        CACHE_DATE: "2025-12-11-v2"

    container_name: truynes-monitor
    restart: unless-stopped
    ports:
      - "9876:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Istanbul
