services:
  mini-monitor:
    build: https://github.com/TRUYNES/mini-monitor.git#main
    container_name: mini-monitor
    restart: unless-stopped
    ports:
      - "9876:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Istanbul
